theme = "gruvbox"

[editor]
auto-info = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

# Hard-wrap the selection at text-width (Vim's gq)
[keys.normal.g]
q = ":reflow"

[keys.select.g]
q = ":reflow"
